### ISSUE TITLE
Issues on the revised key entry forms

### ISSUE THREAD

**Issue by smachua** [opencdms/Climsoft#574]
@Patowhiz and @maxwellfundi thanks for the work done on revising the key entry forms. However, they have issues that are making them unusable. See the list below and have those issues addressed.

1. Key Entry Forms List
    a.	Display adjustment removed from previous code. Had been designed to have the dialog
        height adjust according to the number of forms selected without any empty row shown. The 
         current display has many empty rows for instance if its only one form that is selected.
2. Issues on Key Entry Forms
    a.	form_synoptic_RA1
      •	It is not opening.
    b.	form_hourlywind
      •	Entries not matching with their respective fields in the underlying table. Some values are 
        saved in Flag fields and all flags are saved in Values fields.
      •	Error on Uplading -  (Error Authentication to host 'localhost' for user 'root' using method 
        'mysql_native_password' failed with message: Access denied for user 'root'@'localhost' 
        (using password: NO)).
    c.	form_daily2
      •	Missing Text Box for – “Assign same value to all obs”,
      •	Add New not sequencing to the next new record and Flags not clearing,
      •	Error on uploading – (DBNull to type string invalid).
    d.	Form_hourly
      •	On key entry, text box for Hour 19 is skips on both Enter and Tab keys.  The same text box 
        also not working as expected on Delete and Insert Cell actions,
      •No action on Upload button.
 3. Issues common with all forms
    a. On key entry when a user changes Element on the Element textbox the QC refers to the 
        previous Element,
   b.	Except on “form_hourlywind”, no QC error message shown on ENTER key until the next text 
       box is Clicked.

**Comment by smachua** [comment]
@Patowhiz what I meant by 'empty rows' is in the view of Climsoft operators but not in terms of data. 

In many cases this dialog is used by data operators who have been hired for key entry only. They may not get trained on any other Climsoft operations because they are casuals. To ensure they always select the right form a design that avoids scrolling was adopted in case the listed forms are many. The listview height is adjusted at run time depending on the number of selected forms. 
If the current design is to be changed as you suggested a discussion may be necessary and the documentation be changed as well.

Comparisons of the dialogs:
- Current
![image](https://user-images.githubusercontent.com/12034121/64850180-942ec700-d61d-11e9-82a7-955cc6fb5e29.png)

- Proposed
![image](https://user-images.githubusercontent.com/12034121/64850217-a6a90080-d61d-11e9-9354-8dccdbd2ae70.png)

**Comment by Patowhiz** [comment]
@smachua the changes I made were reviewed and merged by @mhabimana, I wasn't aware of the feature that you have stated above. 

For clarity, so the form changes it's height based on the number of items in the listview? If they are 20, it adjusts to show all the 20 instead of the user scrolling to see the 20th item? If they are say, 3, it reduces its height to accommodate the 3?

I changed the design because I thought having a fixed height was enough for the purpose of the height, and the solution was simple to achieve the purpose of the form since we have our listview that is scrollable. 

But If the form height auto adjustment was found to have an added advantage when users were using it then I'm happy to return the feature. I didn't see the code that that was doing this in the form, did you use the visual designer to achieve this?

**Comment by smachua** [comment]
@Patowhiz and @maxwellfundi we hope the issues listed above will be resolved soon. Some key entry forms could not be used after the changes were merged. At the same time we want to compile a new setup so that users can benefit from improvements made in other areas. May be that particular merging can be reverted so that the forms can be used in the earlier state while you are working on those issues.

**Comment by mhabimana** [comment]
@Patrick - Remember to address as well the issue of future dates on all the data entry forms. In case a future date is typed in the form,the form become inactive,this is how it used to work.

**Comment by mhabimana** [comment]
@Patowhiz - Any progress in addressing above mentioned issues( issue#574). We are waiting for you to address these issues to be able to release a new setup addressing some of the bugs and improvement made so far on Climsoft. Note that most of the data entry forms which are in the master now are not stable and cannot be used in operation. If you are not ready to address these, kindly let me know so that we seek ways to revert back Data Entry Forms to the previous stable state.

**Comment by mhabimana** [comment]
@Patowhiz - I am not sure if you have address Point 3 at the above regarding QC check at the key entry form: e.g when you type the value,higher or lower than the limit,what will be the response?Currently,there is no response,unless the change of the color,and you get stack at the text box unless you move the cursor the the next text box is when the check is done. In real situation,when you type a higher/lower value than the limit and click the enter key (validation),you should get an error message and after correction,you move to the next text box.

**Comment by Patowhiz** [comment]
@mhabimana I have fixed that in my last commit. Check PR #586 . The changes made in that PR will be available to other forms once merged

**Comment by mhabimana** [comment]
@Patowhiz 👍

**Comment by smachua** [comment]
@Patowhiz I looked at the merged code and found that the issues on the key entry forms have been well addressed albeit few areas. Below are my observations on the current status of the forms. See if you can address the few points I have raised and consider the recommendations I have made on forms modifications.

1.	Key Entry Forms List
The grid list adjusts according to the number of selected forms but the entire dialog is fixed. Hence not all forms can be seen if more than 14 are selected. However, it’s not common to list even more than 3 forms. But it will look better if the design caters for all.

2a form_synoptic_RA1
• It is not opening. – Now opening OK
• While entering data in "Auto Fill Values" mode an error message “Attempted to divide by zero” occurs on exiting the "Wetbulb Temp" text box.
• Grass Min Temp text box should be enabled for 06 Hour
• Doesn’t upload records with” M” Flag (i.e. Missing)

2b. form_hourlywind
• No error message reported while uploading
• Doesn’t upload records with” M” Flag (i.e. Missing)

2c. form_daily2
•  “Assign same value to all obs” - 	Text box now present
• Doesn’t upload records with” M” Flag (i.e. Missing)
• Add New now sequencing to the next new record and Flags are clearing,
• No error message reported while uploading
• It doesn’t upload records with” M” Flag (i.e. Missing)

2d. Form_hourly
• It doesn’t upload records with” M” Flag (i.e. Missing)
• Other issues resolved.

3.  Issues common with all forms
• QC now works ok.
• Not uploading records with” M” Flag

Some recommendations on the forms design 
(i) Error trapping
In some rare cases though a bad practice a station or element name may be NULL. While open the forms I encounter  "unhandled exception error" in those cases. I recommend that you modify the code to trap such an error and provide an appropriate message so that users can know and update the affected metadata accordingly. Otherwise the program crashes.

(ii) ucrFormDaily2 – Broken sequence in naming of controls
The names of controls for Day 11 to Day 20 are not in sequence with the rest of controls in that form. Note Day 11 = ucrValueFlagPeriod20, Day 12 =ucrValueFlagPeriod19 ... Day20=ucrValueFlagPeriod11

Although this doesn’t affect data entry operations for now, I recommend that you modify the code to maintain the same naming sequence on all controls in that form.

**Comment by mhabimana** [comment]
@Patowhiz :This issue raised by @smachua is still there:
2d. Form_hourly
• It doesn’t upload records with” M” Flag (i.e. Missing)

**Comment by mhabimana** [comment]
@Patowhiz - The form_synoptic_RA1 need further review.
E.g: Enabling or disabling some text boxes for some hours (E.g:Grass Min Temp and Precip-24Hr text boxes should be enabled for 06 Hour,TMax enabled at 06 and 18 Hour and TMin enabled at 06 Hour,TMin disabled at 18 Hours, disable both TMax and TMin at 0 Hour).

**Comment by mhabimana** [comment]
@Patowhiz -Ignore my previous msg on the synoptic form.

**Comment by mhabimana** [comment]
@Patowhiz -The issue which need to be revised on the synoptic from_2_ra1 is the the transfer of Flags values (e.g.M) in the observationinitial table. These are not being transferred when the upload button is clicked and yet they should be.

**Comment by mhabimana** [comment]
@Patowhiz : Form Hourlywind does not transfer flag values as well into obsinitial table.

**Comment by Patowhiz** [comment]
Fixed that in the validation changes PR

**Comment by mhabimana** [comment]
@Patowhiz - Have you had the chance to look at  this form synoptic from_2_ra1, the transfer of Flags values (e.g.: M) is still not effected in the observationinitial table.

**Comment by Patowhiz** [comment]
@mhabimana please go ahead and test this upload in my PR. It's now working from my end.

**Comment by Patowhiz** [comment]
Now working on the null element codes. Though I noticed that the current database doesn't accept null element code (looking at the database schema). When do the null get input in the database? I expect these nulls to be flagged during the migration.

**Comment by smachua** [comment]
@Patowhiz I hope I got your point. The elements (i.e. observation parameters) are identified by their codes. Am not sure how an observation can be used if it can't be identified. That's why null element codes and null station ids are not allowed in the database.
